src/Blog.Web/Areas/Admin/Controllers/ManageUsersController.cs
using Blog.DataLayer.Context;
using Blog.Entities;
using Blog.Entities.Identity;
using Blog.ViewModels.Users;
using Microsoft.AspNetCore.Authorization;

namespace Blog.Web.Areas.Admin.Controllers;

[Authorize, Area(AreaConstants.Admin)]
public class ManageUsersController : Controller
{
    private readonly IUserManagerService _userManager;
    private readonly IRoleManagerService _roleManager;
    private readonly IUserInformationService _userInformationService;
    private readonly IUnitOfWork _uow;
    private readonly IMapper _mapper;
    public ManageUsersController(IUserManagerService userManager, IRoleManagerService roleManager,IUserInformationService userInformationService,IUnitOfWork uow,IMapper mapper)
    {
        _userManager = userManager;
        _roleManager = roleManager;
        _userInformationService = userInformationService;
        _uow = uow;
        _mapper= mapper;
    }

    public IActionResult Index(UserFiltersAndPaginationViewModel filters)
        => View(_userManager.GetUsersWithFilterAndPagination(filters));


    public IActionResult Statistics()
        => View(_userManager.GetUsersStatistics());

    public async Task<JsonResult> Details(int id)
        => Json(await _userManager.GetUserDetailsForAdminAsync(id));

    #region UserRoles

    public async Task<IActionResult> EditUser(int id)
    {
        var model = await _userManager.GetUserRolesToEditAsync(id);
        if (model is null) return View("Error", PublicErrorMessages.ErrorTryAgain);
        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> EditUser(EditUserRolesViewModel model)
    {
        if (!ModelState.IsValid || !(await _roleManager.CheckRolesAsync(model.Roles)))
        {
            ModelState.AddModelError(string.Empty, PublicErrorMessages.ModelStateErrorMessage);
            return View(model);
        }

        var user = await _userManager.FindByIdAsync(model.Id.ToString());
        if (user is null) return View("Error", PublicErrorMessages.ErrorTryAgain);
        var userInformation = await _userInformationService.GetUserInformationByUserIdAsync(model.Id);
        if (userInformation is null) return View("Error", PublicErrorMessages.SystemError);

        var roles = await _userManager.GetRolesAsync(user);
        await _userManager.RemoveFromRolesAsync(user, roles);
        await _userManager.AddToRolesAsync(user, model.Roles);

        user.DisplayName = model.DisplayName;
        userInformation.Biography = model.Biography;
        userInformation.Website = model.Website;
        userInformation.Instagram = model.Instagram;
        userInformation.Twitter = model.Twitter;
        userInformation.Linkedin = model.Linkedin;

        if (model.NewAvatar is not null && model.NewAvatar.Length > 0)
        {
            var avatarName = Guid.NewGuid().ToString("N");
            var avatarExtension = Path.GetExtension(model.NewAvatar.FileName);
            if (user.Avatar != PublicConstantStrings.UserDefaultAvatar)
            {
                user.Avatar.RemoveImage(ImageFolders.Avatars);
            }
            model.NewAvatar.SaveImage(avatarName, avatarExtension, ImageFolders.Avatars);
            user.Avatar = avatarName + avatarExtension;
        }

        _userInformationService.Update(user.UserInformation);
        _uow.SaveChanges();
        var result = await _userManager.UpdateAsync(user);
        if (result.Succeeded)
        {
            return RedirectToAction(nameof(Index));
        }
        foreach (var error in result.Errors) ModelState.AddModelError(string.Empty, error.Description);

        return RedirectToAction(nameof(Index));
    }
    #endregion

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> ChangeUserActive(int userId)
    {
        var user = await _userManager.FindByIdAsync(userId.ToString());
        if (user is null) return View("Error", PublicErrorMessages.ErrorTryAgain);
        user.IsActive = !user.IsActive;
        var result = await _userManager.UpdateAsync(user);
        if (!result.Succeeded) return View("Error", PublicErrorMessages.SystemError);
        return RedirectToAction(nameof(Index));
    }
}

src/Blog.Web/Areas/Admin/Views/ManageUsers/EditUser.cshtml
@using Blog.ViewModels.Roles;
@using Blog.Services.Contracts.Identity;
@model EditUserRolesViewModel
@inject IRoleManagerService _roleManager;
@{
    ViewData["Title"] = "ویرایش نقش های کاربر";
    var roles = _roleManager.GetAllRoleNames();
}
<h3 class="bg-soft-info p-3 mx-2 rounded-3 text-dark text-center">ویرایش نقش های کاربر</h3>
<div class="bg-soft-info text-dark rounded-3 mx-2 p-3 text-center">
    <div class="row">
        <div class="col-md-4">
            <img src="/images/avatars/@Model.Avatar" class="avatar avatar-medium rounded-circle shadow" id="modelAvatar">
        </div>
        <div class="col-md-6">
            <h4>@Model.UserName</h4>
            <h5 class="text-muted">@Model.Email</h5>
        </div>
    </div>
    <div class="row text-start">
        <form asp-action="EditUser" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="Id"/>
        <div class="row mt-4">
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label" asp-for="DisplayName"></label>
                    <div class="form-icon position-relative">
                        <i class="icons mdi mdi-account"></i>
                        <input asp-for="DisplayName" class="form-control ps-5">
                        <span asp-validation-for="DisplayName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label" asp-for="NewAvatar"></label>
                    <div class="form-icon position-relative">
                        <i class="icons mdi mdi-image"></i>
                        <input asp-for="NewAvatar" class="form-control ps-5">
                        <span asp-validation-for="NewAvatar" class="text-danger"></span>
                    </div>
               </div>
            </div>
            <div class="col-md-12">
                <div class="mb-3">
                    <label class="form-label" asp-for="Biography"></label>
                    <div class="form-icon position-relative">
                        <i class="icons mdi mdi-card-text"></i>
                        <textarea asp-for="Biography" class="form-control ps-5"></textarea>
                        <span asp-validation-for="Biography" class="text-danger"></span>
                    </div>
               </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label" asp-for="Website"></label>
                    <div class="form-icon position-relative">
                        <i class="icons mdi mdi-web"></i>
                        <input asp-for="Website" class="form-control ps-5">
                        <span asp-validation-for="Website" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label" asp-for="Instagram"></label>
                    <div class="form-icon position-relative">
                        <i class="icons mdi mdi-instagram"></i>
                        <input asp-for="Instagram" class="form-control ps-5">
                        <span asp-validation-for="Instagram" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label" asp-for="Twitter"></label>
                    <div class="form-icon position-relative">
                        <i class="icons mdi mdi-twitter"></i>
                        <input asp-for="Twitter" class="form-control ps-5">
                        <span asp-validation-for="Twitter" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="mb-3">
                    <label class="form-label" asp-for="Linkedin"></label>
                    <div class="form-icon position-relative">
                        <i class="icons mdi mdi-linkedin"></i>
                        <input asp-for="Linkedin" class="form-control ps-5">
                        <span asp-validation-for="Linkedin" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-md-12">
                <div class="mb-3">
                    @foreach (var item in roles)
                    {
                        <div>
                            <input class="form-check-input" type="checkbox" value="@item" name="Roles"
                                @(Model.Roles.Any(r => r == item.ToString())?"checked":"")>
                            <label class="form-label">@item</label>
                        </div>
                    }
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <button type="submit" class="btn btn-info w-100">ثبت</button>
            </div>
        </div>
    </form>
    </div>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

src/Blog.Web/Areas/Admin/Views/ManageUsers/Index.cshtml
@model SearchingUsersViewModels
@{
    ViewData["Title"] = "لیست کاربران";
}

<div class="row justify-content-center mb-3">
    <div class="col-md-12">
        <div class="card shadow rounded border-0">
            <div class="card-body">
                <h6 class="card-title">جستجو</h6>
                <form asp-action="Index" id="filter-form"
                    method="get" class="mt-4">
                    <input asp-for="@Model.filters.CurrentPage"/>
                    <div class="row">
                        <div asp-validation-summary="ModelOnly" class="text-danger" id="vlidation-summary">
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.filters.UserName"></label>
                                <div class="form-icon position-relative">
                                    <i class="icons mdi mdi-account"></i>
                                    <input class="form-control ps-5" asp-for="@Model.filters.UserName"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                <label class="form-label" asp-for="@Model.filters.Email"></label>
                                <div class="form-icon position-relative">
                                    <i class="icons mdi mdi-account"></i>
                                    <input class="form-control ps-5" asp-for="@Model.filters.Email"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                 <label class="form-label" asp-for="@Model.filters.ActiveStatus"></label>
                                 <select class="form-select form-control" asp-for="@Model.filters.ActiveStatus" asp-items="@Model.filters.ActiveStatusItems"></select>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="mb-3">
                                 <label class="form-label" asp-for="@Model.filters.EmailConfirmedStatus"></label>
                                 <select class="form-select form-control" asp-for="@Model.filters.EmailConfirmedStatus" asp-items="@Model.filters.EmailConfirmedStatusItems"></select>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary">جستجو</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@if (Model.Users.Any())
{
    <div class="table-responsive bg-white shadow rounded">
        <table class="table mb-0 table-center">
            <thead>
                <tr>
                    <th scope="col" class="border-bottom">@Html.DisplayNameFor(model => model.Users.First().Avatar)</th>
                    <th scope="col" class="border-bottom">@Html.DisplayNameFor(model => model.Users.First().UserName)</th>
                    <th scope="col" class="border-bottom">@Html.DisplayNameFor(model => model.Users.First().Email)</th>
                    <th scope="col" class="border-bottom">@Html.DisplayNameFor(model => model.Users.First().CreatedDateTime)</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Users)
                {
                    <tr @(!item.IsActive? "class=bg-soft-danger":"") data-bs-target="#user-card" data-bs-toggle="modal" onclick="ShowUserDetails(@item.Id)">
                        <td><img src="~/images/avatars/@item.Avatar" class="img-fluid avatar avatar-md-sm me-2 rounded-circle"/></td>
                        <td>@item.UserName</td>
                        <td @(!item.EmailConfirmed? "class=bg-soft-warning":"")>@item.Email</td>
                        <td>@item.CreatedDateTime.ToLongPersianDateTimeString()</td>
                    </tr>
                }
            </tbody>
        </table>
</div>
    <div class="d-flex justify-content-center mt-3">    
    <ul class="pagination mb-0">
        <li class="page-item"><button class="page-link @(Model.filters.CurrentPage == 1?"btn btn-mute":"")" @(Model.filters.CurrentPage == 1?"disabled":"") value="@(Model.filters.CurrentPage - 1)">قبلی </button></li>
        @for (int counter = 1; counter <= Model.filters.PagesCount; counter++)
        {
            <li class="page-item @(Model.filters.CurrentPage == counter? "active":"")">
                 <button class="page-link" name="page" value="@counter">@counter</button>
            </li>
        }
        <li class="page-item"><button class="page-link @(Model.filters.CurrentPage == Model.filters.PagesCount?"btn btn-mute":"")" @(Model.filters.CurrentPage == Model.filters.PagesCount?"disabled":"") value="@(Model.filters.CurrentPage + 1)">بعدی </button></li>
    </ul>
</div>
}
else
{
    <div class="alert bg-soft-warning text-center">
        <h4 class="alert-heading">موردی یافت نشد</h4>
        <p>با توجه به فیلتر های وارد شده موردی یافت نشد</p>
    </div>
}

<div class="modal fade" id="user-card" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content rounded shadow border-0">
            <div class="modal-body py-5">
                <div class="text-center">
                    <img src="" class="avatar avatar-medium rounded-circle shadow" id="modelAvatar">
                    <div class="mt-4">
                        <h4 id="modalUserName"></h4>
                        <h5 id="modalEmail"></h5>
                        <p class="text-muted" id="modalCreatedDateTime"></p>
                        <div class="bg-soft-info text-dark d-none" id="externalLogins">
                            <span class="text-muted">ورود های خارجی : </span>
                            <p></p>
                        </div>
                        <div class="mt-4">
                            <a id="modalRolesLink" class="btn btn-soft-info w-100" >ویرایش نقش ها</a>
                        </div>
                        <div class="mt-4">
                            <form asp-action="ChangeUserActive" asp-controller="ManageUsers" asp-area="Admin">
                                <button class="btn w-100" id="modalActiveButton" name="userId"></button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $('#ManageUsers').addClass('active');
        $('.page-link').click(function(el){
            $('#filters_CurrentPage').val(el.target.value);
            $('#filter-form').submit();
        });

        function ShowUserDetails(userId) {
            $.get( "/Admin/ManageUsers/Details/"+userId,
                function(data,status){
                    $('#modelAvatar').attr('src','/images/avatars/'+data.avatar);
                    //$('#modalRolesLink').attr('href','/Admin/ManageUsers/EditUser?userId='+data.id);
                    $('#modalRolesLink').attr('href','/Admin/ManageUsers/EditUser/'+data.id);
                    if(!data.emailConfirmed){
                        $('#modalEmail').addClass('text-danger');
                    }else{
                        $('#modalEmail').removeClass('text-danger');
                    }
                    $('#modalUserName').html(data.userName);
                    $('#modalEmail').html(data.email);
                    $('#modalCreatedDateTime').html(data.createdDateTime);
                    $('#modalActiveButton').val(data.id);
                    $('#externalLogins').addClass('d-none');
                    $('#externalLogins>p').html('');
                    if(data.externalLogins.length > 0){
                        $('#externalLogins').removeClass('d-none');
                        data.externalLogins.forEach(function(element){
                            $('#externalLogins>p').append(element+'<br/>');
                        });
                    }
                    if(data.isActive){
                        $('#modalActiveButton').removeClass('btn-success');
                        $('#modalActiveButton').addClass('btn-danger');
                        $('#modalActiveButton').html('غیر فعال سازی');
                    }else{
                        $('#modalActiveButton').removeClass('btn-danger');
                        $('#modalActiveButton').addClass('btn-success');
                        $('#modalActiveButton').html('فعال سازی');
                    }
                    console.log(data);
                });
        }
    </script>
}

src/Blog.Web/Areas/Admin/Views/ManageUsers/Statistics.cshtml
@model UsersStatisticsViewModel
@{
    ViewData["Title"] = "Statistics";
}
<div class="row">
    <div class="col-md-4 mt-3">
        <div class=" h-100 card bg-soft-info text-dark text-center justify-content-center">
            <h2>@Model.UsersCount.ToPersianNumbers("N0")</h2>
            <p class="text-muted">@Html.DisplayNameFor(m => m.UsersCount)</p>
        </div>
    </div> 
    <div class="col-md-8 mt-2">
        <div class="row">
            <div class="col-md-12 mt-2">
                <div class="card bg-soft-info text-dark text-center">
                    <h2>@Model.ConfirmedUsersCount.ToPersianNumbers("N0")</h2>
                    <p class="text-muted">@Html.DisplayNameFor(m => m.ConfirmedUsersCount)</p>
                </div>
            </div>
            <div class="col-md-6 mt-2">
                <div class="card bg-soft-info text-dark text-center">
                    <h2>@Model.ActiveUsersCount.ToPersianNumbers("N0")</h2>
                    <p class="text-muted">@Html.DisplayNameFor(m => m.ActiveUsersCount)</p>
                </div>
            </div> 
            <div class="col-md-6 mt-2">
                <div class="card bg-soft-info text-dark text-center">
                    <h2>@Model.ConfirmedEmailUsersCount.ToPersianNumbers("N0")</h2>
                    <p class="text-muted">@Html.DisplayNameFor(m => m.ConfirmedEmailUsersCount)</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 mt-3">
        <div class=" h-100 card bg-soft-info text-dark text-center justify-content-center">
            <h2>@Model.RegistrationLastThirtyDaysCount.ToPersianNumbers("N0")</h2>
            <p class="text-muted">@Html.DisplayNameFor(m => m.RegistrationLastThirtyDaysCount)</p>
        </div>
    </div> 
    <div class="col-md-6 mt-3">
        <div class=" h-100 card bg-soft-info text-dark text-center justify-content-center">
            <h2>@Model.RegistrationLastSevenDaysCount.ToPersianNumbers("N0")</h2>
            <p class="text-muted">@Html.DisplayNameFor(m => m.RegistrationLastSevenDaysCount)</p>
        </div>
    </div> 
    <div class="col-md-6 mt-3">
        <div class=" h-100 card bg-soft-info text-dark text-center justify-content-center">
            <h2>@Model.ExternalLogins.ToPersianNumbers("N0")</h2>
            <p class="text-muted">@Html.DisplayNameFor(m => m.ExternalLogins)</p>
        </div>
    </div> 
</div>
@section Scripts{
    <script>
        $('#ManageUsersStatistics').addClass('active');
    </script>
}