src/Blog.Web/Areas/Admin/Controllers/ManageRolesController.cs
using Blog.Entities;
using Blog.Entities.Identity;
using Blog.ViewModels.Roles;
using Microsoft.AspNetCore.Authorization;
using NuGet.Packaging;

namespace Blog.Web.Areas.Admin.Controllers;

[Authorize, Area(AreaConstants.Admin)]
public class ManageRolesController : Controller
{
    IRoleManagerService _roleManager;
    IMapper _mapper;
    public ManageRolesController(IRoleManagerService roleManager, IMapper mapper)
    {
        _roleManager = roleManager;
        _mapper = mapper;
    }
    public IActionResult Index(string filter, int page = 1)
        => View(_roleManager.GetRolesWithFilterAndPagination(filter, page));

    #region AddRole
    public IActionResult AddRole() => View();

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> AddRole(AddRoleViewModel model)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError(string.Empty, PublicErrorMessages.ModelStateErrorMessage);
            return View(model);
        };
        var role = _mapper.Map<Role>(model);
        var result = await _roleManager.CreateAsync(role);
        if (!result.Succeeded)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(model);
        }
        return RedirectToAction("Index");
    }
    #endregion
    #region EditRole
    public async Task<IActionResult> EditRole(int id)
    {
        var model = await _roleManager.GetRoleToEditAsync(id);
        if (model is null) return View("Error", PublicErrorMessages.ErrorTryAgain);
        //if(model.) //TODO : check system roles not edit permissions
        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> EditRole(EditRoleViewModel model)
    {
        if (!ModelState.IsValid)
        {
            ModelState.AddModelError(string.Empty, PublicErrorMessages.ModelStateErrorMessage);
            return View(model);
        };
        var role = await _roleManager.GetRoleToUpdateAsync(model.Id);
        if (role is null) return View("Error", PublicErrorMessages.ErrorTryAgain);
        role.Name = model.Name;
        role.RolePermissions.Clear();
        role.RolePermissions.AddRange(model.Permissions.Select(rp => new RolePermission()
        {
            Permission = rp,
        }));

        var result = await _roleManager.UpdateAsync(role);
        if (!result.Succeeded)
        {
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }
            return View(model);
        }
        return RedirectToAction("Index");
    }
    #endregion

    public async Task<IActionResult> RoleDetails(int id)
    {
        var model = await _roleManager.GetRoleDetailsById(id);
        if (model is null) return View("Error", PublicErrorMessages.ErrorTryAgain);
        return View(model);
    }

    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteRole(string id)
    {
        var role = await _roleManager.FindByIdAsync(id);
        if (role is null) return View("Error", PublicErrorMessages.ErrorTryAgain);
        var result = await _roleManager.DeleteAsync(role);
        if (!result.Succeeded) return View("Error", PublicErrorMessages.SystemError);
        return RedirectToAction("Index");
    }

    public IActionResult RolePermissions()
        => View(typeof(ManageRolesController).Assembly.GetAreaControllerActionNames()
        .Where(m => m.Area == AreaConstants.Admin));
}

src/Blog.Web/Areas/Admin/Views/ManageRoles/AddRole.cshtml
@using Blog.ViewModels.Roles;
@using Blog.Web.Areas.Admin.Controllers;
@using Blog.Common.Extensions
@model AddRoleViewModel
@{
    ViewData["Title"] = "افزودن نقش";
    var permissions = typeof(ManageRolesController).Assembly.GetAreaControllerActionNames().Where(a => a.Area == "Admin").Distinct().ToList();
}
<h3 class="bg-soft-info p-3 mx-2 rounded-3 text-dark text-center">افزودن نقش</h3>
<div class="bg-soft-info text-dark rounded-3 mx-2 p-3">
    <form method="post" asp-action="AddRole">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="col-md-12">
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <div class="form-icon position-relative">
                    <i class="icons mdi mdi-account"></i>
                    <input asp-for="Name" class="form-control ps-5">
                    <span asp-validation-for="Name" class="text-danger"></span><br />
                </div>
            </div>
        </div>
        <label class="form-label">@Html.DisplayNameFor(model => model.Permissions)</label>
        <div class="col-md-12 text-end" dir="ltr">
            <div class="table-responsive bg-white shadow rounded text-end" dir="ltr">
                <table class="table mb-0 table-center">
                    <thead>
                        <tr>
                            <th scope="col" class="border-bottom">✔</th>
                            <th scope="col" class="border-bottom">Area</th>
                            <th scope="col" class="border-bottom">Controller</th>
                            <th scope="col" class="border-bottom">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in permissions)
                        {
                            <tr>
                                <td>
                                 <input class="form-check-input" type="checkbox" value="@item.GetAll" name="Permissions">
                                </td>
                                <td>@item.Area</td>
                                <td>@item.Controller</td>
                                <td>@item.Action</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-12 mt-2">
            <button class="btn btn-info w-100">ثبت</button>
        </div>
    </form>
</div>
@section Scripts{
<partial name="_ValidationScriptsPartial"/>
    <script>
        $('#AddRole').addClass('active');
    </script>
}

src/Blog.Web/Areas/Admin/Views/ManageRoles/EditRole.cshtml
@using Blog.ViewModels.Roles;
@using Blog.Web.Areas.Admin.Controllers;
@using Blog.Common.Extensions
@model EditRoleViewModel
@{
    ViewData["Title"] = "ویرایش نقش";
    var permissions = typeof(ManageRolesController).Assembly.GetAreaControllerActionNames().Where(a => a.Area == "Admin").Distinct().ToList();
}
<h3 class="bg-soft-info p-3 mx-2 rounded-3 text-dark text-center">ویرایش نقش</h3>
<div class="bg-soft-info text-dark rounded-3 mx-2 p-3">
    <form method="post" asp-action="EditRole">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input asp-for="Id"/>
        <div class="col-md-12">
            <div class="mb-3">
                <label asp-for="Name" class="form-label"></label>
                <div class="form-icon position-relative">
                    <i class="icons mdi mdi-account"></i>
                    <input asp-for="Name" class="form-control ps-5">
                    <span asp-validation-for="Name" class="text-danger"></span><br />
                </div>
            </div>
        </div>
        <label class="form-label">@Html.DisplayNameFor(model => model.Permissions)</label>
        <div class="col-md-12 text-end" dir="ltr">
            <div class="table-responsive bg-white shadow rounded text-end" dir="ltr">
                <table class="table mb-0 table-center">
                    <thead>
                        <tr>
                            <th scope="col" class="border-bottom">✔</th>
                            <th scope="col" class="border-bottom">Area</th>
                            <th scope="col" class="border-bottom">Controller</th>
                            <th scope="col" class="border-bottom">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in permissions)
                        {
                            <tr>
                                <td>
                                 <input class="form-check-input" type="checkbox" value="@item.GetAll" name="Permissions"
                                    @(Model.Permissions.Any(p => p == item.GetAll)? "checked":"")>
                                </td>
                                <td>@item.Area</td>
                                <td>@item.Controller</td>
                                <td>@item.Action</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
        <div class="col-md-12 mt-2">
            <button class="btn btn-info w-100">ثبت</button>
        </div>
    </form>
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

src/Blog.Web/Areas/Admin/Views/ManageRoles/Index.cshtml
@model RolesWithFilterAndPaginationViewModel
@{
    ViewData["Title"] = "لیست کاربران";
}
<div class="row justify-content-center mb-3">
    <div class="col-md-12">
        <div class="card shadow rounded border-0">
            <div class="card-body">
                <form asp-action="Index" id="filter-form"
                    method="get" class="mt-4">
                    <input asp-for="@Model.CurrentPage" name="page"/>
                    <div class="row">
                        <div asp-validation-summary="ModelOnly" class="text-danger" id="vlidation-summary">
                        </div>
                        <div class="col-md-8">
                            <div class="mb-3">
                                <div class="form-icon position-relative">
                                    <i class="icons mdi mdi-magnify"></i>
                                    <input class="form-control ps-5" asp-for="SearchKey" name="filter"/>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-4">
                            <div class="d-grid">
                                <button type="submit" class="btn btn-primary">جستجو</button>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
<div class="row mx-1 mb-3">
    <a asp-action="AddRole" asp-controller="ManageRoles" asp-area="Admin" class="btn btn-info">افزودن نقش</a>
</div>
@if (Model.Roles.Any())
{
    <div class="table-responsive bg-white shadow rounded">
        <table class="table mb-0 table-center">
            <thead>
                <tr>
                    <th scope="col" class="border-bottom">@Html.DisplayNameFor(model => model.Roles.First().Name)</th>
                    <th scope="col" class="border-bottom">@Html.DisplayNameFor(model => model.Roles.First().UsersInRoleCount)</th>
                    <th scope="col" class="border-bottom">عملیات</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Roles)
                {
                    <tr>
                        <td>@item.Name</td>
                        <td>@item.UsersInRoleCount</td>
                        <td>
                            <a asp-action="RoleDetails" asp-controller="ManageRoles" asp-area="Admin" asp-route-Id="@item.Id" class="btn btn-soft-info">اطلاعات</a>
                            <a asp-action="EditRole" asp-controller="ManageRoles" asp-area="Admin" asp-route-Id="@item.Id" class="btn btn-soft-success">ویرایش</a>
                            <a data-bs-target="#confirm-delete-card" data-bs-toggle="modal" onclick="ShowDeleteConfirmModal(@item.Id)" class="btn btn-soft-danger">حذف</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
</div>
    <div class="d-flex justify-content-center mt-3">    
    <ul class="pagination mb-0">
        <li class="page-item"><button class="page-link @(Model.CurrentPage == 1?"btn btn-mute":"")" @(Model.CurrentPage == 1?"disabled":"") value="@(Model.CurrentPage - 1)">قبلی </button></li>
        @for (int counter = 1; counter <= Model.PagesCount; counter++)
        {
            <li class="page-item @(Model.CurrentPage == counter? "active":"")">
                 <button class="page-link" name="page" value="@counter">@counter</button>
            </li>
        }
        <li class="page-item"><button class="page-link @(Model.CurrentPage == Model.PagesCount?"btn btn-mute":"")" @(Model.CurrentPage == Model.PagesCount?"disabled":"") value="@(Model.CurrentPage + 1)">بعدی </button></li>
    </ul>
</div>
}
else
{
    <div class="alert bg-soft-warning text-center">
        <h4 class="alert-heading">موردی یافت نشد</h4>
        <p>با توجه به فیلتر های وارد شده موردی یافت نشد</p>
    </div>
}

<div class="modal fade" id="confirm-delete-card" tabindex="-1" style="display: none;" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content rounded shadow border-0">
            <div class="modal-body py-5">
                <div class="text-center">
                    <div class="mt-4">
                        <p class="text-danger">آیا از حذف نقش اطمینان دارید؟ این عملیات غیر قابل بازگشت است</p>
                        <div class="mt-4">
                            <form asp-action="DeleteRole" asp-controller="ManageRoles" asp-area="Admin" method="post">
                                <button class="btn btn-danger" id="modalDeleteButton" name="id">حذف</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $('#ManageRoles').addClass('active');
        $('.page-link').click(function(el){
            $('#CurrentPage').val(el.target.value);
            $('#filter-form').submit();
        });

        function ShowDeleteConfirmModal(userId) {
            console.log(userId);
            $('#modalDeleteButton').val(userId);
        };
    </script>
}

src/Blog.Web/Areas/Admin/Views/ManageRoles/RoleDetails.cshtml
@using Blog.ViewModels.Roles;
@model RoleDetailsViewModel
@{
    ViewData["Title"] = "اطلاعات نقش";
}
<h3 class="bg-soft-info p-3 mx-2 rounded-3 text-dark text-center">اطلاعات نقش</h3>
<div class="bg-soft-info text-dark rounded-3 mx-2 p-3 text-center">
    <h4>@Model.Name</h4><hr />
    <span class="text-muted me-2">@Html.DisplayNameFor(model => model.UsersInRoleCount)</span>
    <h4>@Model.UsersInRoleCount.ToPersianNumbers()</h4><hr />
    <span class="text-muted me-2 text-start">@Html.DisplayNameFor(model => model.Permissions)</span>
    <div class="text-end">
    @foreach (var item in Model.Permissions)
    {
        <p>@item.Replace("|","  /  ")</p>
    }
    </div>
</div>

src/Blog.Web/Areas/Admin/Views/ManageRoles/RolePermissions.cshtml
@model IEnumerable<Blog.Common.Extensions.AreaControllerActionName>
@{
    ViewData["Title"] = "لیست دسترسی ها";
}
<div class="table-responsive bg-white shadow rounded text-end" dir="ltr">
    <table class="table mb-0 table-center">
        <thead>
            <tr>
                <th scope="col" class="border-bottom">@Html.DisplayNameFor(model => model.First().Area)</th>
                <th scope="col" class="border-bottom">@Html.DisplayNameFor(model => model.First().Controller)</th>
                <th scope="col" class="border-bottom">@Html.DisplayNameFor(model => model.First().Action)</th>
            </tr>
        </thead>
        <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Area</td>
                <td>@item.Controller</td>
                <td>@item.Action</td>
            </tr>
        }
        </tbody>
    </table>
</div>